### ISSUE TITLE
Web page stuck at the customizable_plots tab

### ISSUE THREAD

**Issue by quancs** [abdeladim-s/tensorboard_plugin_customizable_plots#2]
I have more than 400 runs in tensorboard. When I switch to the customizable_plots tab, the page stuck when using Firefox and Edge.

**Comment by absadiki** [comment]
Yeah 400 runs is a huge number, I am not sure if the plugin (and the plotly.js library) can handle that huge amount of data. 

Have you tried to look at the developer console and see if there are any errors there ? 

Have you tried to load a small number of runs instead of the whole directory ? 
```bash
tensorboard --logdir=name1:/path/to/logs/1,name2:/path/to/logs/2
```

**Comment by quancs** [comment]
The tensorboard says: `W0206 17:08:58.745338 140194350093888 application.py:558] path /chart_worker.js.map not found, sending 404`. The dir specified has only 20 runs.
![图片](https://user-images.githubusercontent.com/16813683/216930590-28bdd39d-52e7-456a-96bd-fd7257d448e7.png)

**Comment by quancs** [comment]
The console errors in Firefox for the 20 runs:
![图片](https://user-images.githubusercontent.com/16813683/216931066-53030e16-57e5-4964-b590-612d6738617f.png)

**Comment by quancs** [comment]
In Chrome (seems this page is not clickable):
![图片](https://user-images.githubusercontent.com/16813683/216931554-3e3fe5a4-c392-4f0c-a247-74f07b42b291.png)

**Comment by absadiki** [comment]
* For Firefox, I think the `Content Security Policy` is caused by some installed extension (probably ad-blocker) try to disable the extensions and see.

* For Chrome, it seems to be working, what do you mean by not clickable ? 
 You mean The page is not responsive at all ? You cannot click on anything ? 
If that's the case, I think: 
    * Either the plotly.js library is having a hard time creating the plots instances (from what I notice, the scrollbar shows that you have so many `tags`), every `tag` is a plot created on load time, and that causes the page to stuck. 
    * Either,  the data you working with are a special case that I didn't take into consideration. 

  If you can provide some dummy data close to what you are working with so I can produce the error on my machine, so we can investigated more together ?

**Comment by quancs** [comment]
Firefox shows the figures now after turning off tempermonkey. Chrome works too after I use another computer with more powerful cpu. Following zip is the tensorboard data I used. 
[test.zip](https://github.com/abdeladim-s/tensorboard_plugin_customizable_plots/files/10671263/test.zip)

> Either the plotly.js library is having a hard time creating the plots instances (from what I notice, the scrollbar shows that you have so many tags), every tag is a plot created on load time, and that causes the page to stuck.

Maybe we can consider not drawing the plots on load time, or by default not selecting any runs on load customizable plots page since that drawing all the plots if we have many runs is time-consuming.

**Comment by absadiki** [comment]
Yes I agree, good idea. I was thinking the same yesterday, maybe we should not draw the plots until the `Tag`'s Accordion get expanded. That way we might notice some performance increase on load time, but I am not sure yet how far this can be achieved. 
I was also thinking of using WebGL by default instead of SVG, plotly.js says this increases the speed. 

Thanks for the data. I will give it a try and see if I can replicate the same on my machine. 

I will apply those optimizations and update the plugin asap and will let you know to test on your end.

**Comment by absadiki** [comment]
> Following zip is the tensorboard data I used. [test.zip](https://github.com/abdeladim-s/tensorboard_plugin_customizable_plots/files/10671263/test.zip)

I wanted to try the Tensorboard data but the folders are empty, could you please re-check ?

**Comment by quancs** [comment]
Sorry, I made a mistake when compressing the data. The following is the data I checked.

[SSFNetLM.zip](https://github.com/abdeladim-s/tensorboard_plugin_customizable_plots/files/10681017/SSFNetLM.zip)

**Comment by absadiki** [comment]
Thanks it seems good now.

**Comment by absadiki** [comment]
I finally managed to get a huge performance increase. The Accordions are not loaded now until they get expanded. 
I tested it with your provided data and it seems to work. 

The data is not loaded as well until you expand a `Tag`, so you might notice some delay, but just for the first load time. 

I pushed a new version of the the plugin, please update it and give it a try:

```bash
pip install --upgrade tensorboard-plugin-customizable-plots
```

let me know how it goes ?

**Comment by quancs** [comment]
seems the latest version 1.0.0 is not online yet, see https://pypi.org/project/tensorboard-plugin-customizable-plots/#history.
I tried to install from github `pip install https://github.com/abdeladim-s/tensorboard_plugin_customizable_plots/zipball/master`, but the tensorboard reported an error: 
```
  File "/data/home/quancs/miniconda3/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/data/home/quancs/miniconda3/lib/python3.9/site-packages/tensorboard/main.py", line 42, in run_main
    plugins=default.get_plugins(),
  File "/data/home/quancs/miniconda3/lib/python3.9/site-packages/tensorboard/default.py", line 105, in get_plugins
    return get_static_plugins() + get_dynamic_plugins()
  File "/data/home/quancs/miniconda3/lib/python3.9/site-packages/tensorboard/default.py", line 140, in get_dynamic_plugins
    return [
  File "/data/home/quancs/miniconda3/lib/python3.9/site-packages/tensorboard/default.py", line 141, in <listcomp>
    entry_point.resolve()
  File "/data/home/quancs/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'tensorboard_plugin_customizable_plots'
```

**Comment by absadiki** [comment]
Sorry, seems there a was a problem with the upload, 
Please try with version `1.0.1`.

**Comment by quancs** [comment]
Hello, I tested the version `1.0.1`, it works well.
Thank you for developing this wonderful plugin. ^_^

**Comment by absadiki** [comment]
My pleasure. :) 
'Glad you find it useful!
