### ISSUE TITLE
Suggestion: support regular expression in the filter input widget

### ISSUE THREAD

**Issue by quancs** [abdeladim-s/tensorboard_plugin_customizable_plots#4]
Hello, thank you for making this plugin, it is great, and saves me a lot of time. 

Currently, the filter input widget seems not support regular expressions to filter runs, which is a little bit inconvenient.
For example, the default filter widget in the TIME SERIES tab:
![图片](https://user-images.githubusercontent.com/16813683/218295675-64eaae18-b66f-4284-bfd6-d10c0c3084b7.png)

Below is the result in the CUSTOMIZABLE PLOT:
![图片](https://user-images.githubusercontent.com/16813683/218295735-3f7a8f56-acd7-4300-9d3e-852b25f50182.png)

**Comment by absadiki** [comment]
Hello, 
You are welcome. 'Happy that it helps :) 

Yes you are right. Regular expressions are not supported to filter runs and tags.  
When I was developing the plugin I didn't know if it will be useful for someone, so I just kept a simple filter. 
But yeah, if you have so many runs, you will find it inconvenient. 

If it will help you in your workflow I will add it as well. 
I will let you know when it is done to test it on your end.

**Comment by absadiki** [comment]
@quancs, please update the plugin and give the filter a try now. 
Btw, You don't need to hit `Enter` anymore, the filter will be triggered while you type. 

Let me know if you find any issues.

**Comment by quancs** [comment]
@abdeladim-s The filter works. I find a smal bug that the "select-all" checkbox (marked in the red square) doesn't work as I expected: after filtering runs, seems all runs are drawn if I select the "select-all" checkbox.

![图片](https://user-images.githubusercontent.com/16813683/218356358-2a543ede-57b1-4536-b1ec-13e421b30e79.png)

**Comment by absadiki** [comment]
@quancs, yeah I see, I didn't pay attention to that. 
Thanks for pointing it out. 
I will fix it quickly.

**Comment by absadiki** [comment]
@quancs, please test it now and see if it works as expected ?

There is a small inconvenience though, the checkbox does not have a third state (like the standard Tensorboard plugins), that reflects when just some runs are selected and the others are not. 
So, due to this limitation, the checked state represents the `all or some are checked` state, the not checked state otherwise.

**Comment by quancs** [comment]
Great! It works as expected. Thank you!

**Comment by absadiki** [comment]
You are welcome :)
