### ISSUE TITLE
how to change the order of legend items

### ISSUE THREAD

**Issue by quancs** [abdeladim-s/tensorboard_plugin_customizable_plots#5]
Hello, for the generated figure below, I want to show the items `NBC2-small + 7️⃣`, `NBC2-small + 7️⃣x2`, `NBC2-small + 7️⃣x3` close. How could I achieve that? And would it possible to provide a button to quickly change the colors of the filtered runs? Because often, I find that the filtered runs have close colors hard to distinguish, e.g. the `NBC2-small` and the `NBC2-small + 7️⃣x2`.

![图片](https://user-images.githubusercontent.com/16813683/225581812-f1d35cb6-348e-425c-b227-9a24e300dc4e.png)

**Comment by absadiki** [comment]
Hello,

* I don't really quite understand your question! You mean you want to keep just these 3 runs and hide the other ones ? You can achieve that by filtering the wanted runs and toggle off the ones you don't want. If you want to keep the runs and modify the legend, you can toggle the `show_legend` option under the run's configs. 

* For the colors, I wanted to do the same, but unfortunately, mui does not provide any color-picker component, and I don't want to add more third party libraries to the plugin, so I kept this option manual. I know it's not as quick as a color-picker button, but it does the job. To do it manually, just pick a color from the `TIME SERIES` plugin and copy its hex value, and then change the color property under the run's configs: `<run> -> line -> color` paste the hex value and press Enter. 

I hope this answers your questions ?

**Comment by quancs** [comment]
I mean I want to change the order of the legend items, for example I want to put the `NBC2-small + 7️⃣x2` behind `NBC2-small + 7️⃣`.

![图片](https://user-images.githubusercontent.com/16813683/225787884-a9b6b814-ef2c-44de-83b4-f33d068bc8d3.png)

**Comment by quancs** [comment]
> For the colors, I wanted to do the same, but unfortunately, mui does not provide any color-picker component, and I don't want to add more third party libraries to the plugin, so I kept this option manual. I know it's not as quick as a color-picker button, but it does the job. To do it manually, just pick a color from the TIME SERIES plugin and copy its hex value, and then change the color property under the run's configs: <run> -> line -> color paste the hex value and press Enter.

Yes, I know the color can be changed manually. I just found it is annoying that I often need to change the colors of some runs after re-filtering, because the color of some runs might collide.

**Comment by absadiki** [comment]
> I mean I want to change the order of the legend items, for example I want to put the `NBC2-small + 7️⃣x2` behind `NBC2-small + 7️⃣`.
> 
> ![图片](https://user-images.githubusercontent.com/16813683/225787884-a9b6b814-ef2c-44de-83b4-f33d068bc8d3.png)

Oh the order? you can adjust it using the `legendrank` option under the run's config, by default it is 1000, just set the numbers one by one, 1 will be on top, 2 will be the second and so on ..

**Comment by absadiki** [comment]
> > For the colors, I wanted to do the same, but unfortunately, mui does not provide any color-picker component, and I don't want to add more third party libraries to the plugin, so I kept this option manual. I know it's not as quick as a color-picker button, but it does the job. To do it manually, just pick a color from the TIME SERIES plugin and copy its hex value, and then change the color property under the run's configs:  -> line -> color paste the hex value and press Enter.
> 
> Yes, I know the color can be changed manually. I just found it is annoying that I often need to change the colors of some runs after re-filtering, because the color of some runs might collide.

I don't think it might collide, if you re-filter, the color will stay the same, the other ones will be taken randomly. 
But anyhow, the plugin will be used just when you want to export them, so filter first, then change the colors and then export. 
I know it is not convenient, but at least, better than exporting svg and doing that manually using an image editor software :sweat_smile:

**Comment by quancs** [comment]
@abdeladim-s OK. Thank you~
