### ISSUE TITLE
No response after using legendrank

### ISSUE THREAD

**Issue by MinsGoing** [abdeladim-s/tensorboard_plugin_customizable_plots#8]
I have set the priority in legendrank, but the order of the legends has not changed

**Comment by absadiki** [comment]
I just tested it and it works on my side. The runs with `legendrank` less than 1000 will go first normally! 
I hope you din't forget to hit enter when you changed it ?

**Comment by MinsGoing** [comment]
I hit enter，it still doesn't work.Which version of Tensorboard are you using？

**Comment by absadiki** [comment]
I am using tensorboard `2.13.0`, but I don't think the version of Tensorboard matters as long as the plugin is working. 
I tried to upload a new version to Pypi ([v1.1.2](https://pypi.org/project/tensorboard-plugin-customizable-plots/1.1.2/)). 
Could you please update he plugin to this version and give it a try ?

**Comment by MinsGoing** [comment]
> 

Thanks,I have updated the new version, it's working.How to display the y value corresponding to the same x value on different lines?The previous version can be used directly.

**Comment by absadiki** [comment]
You are welcome. 
I don't understand your request! Could you please explain it more, or show me how it looks on the previous version ?

**Comment by MinsGoing** [comment]
> 

![image](https://github.com/abdeladim-s/tensorboard_plugin_customizable_plots/assets/37976972/ca1ea40e-bcc8-4253-84e6-2d2d767e8680)
![屏幕截图 2023-08-16 105254](https://github.com/abdeladim-s/tensorboard_plugin_customizable_plots/assets/37976972/ab63df85-6e32-4f56-8884-8c5b37ef5737)

The first img is the previous version.

**Comment by absadiki** [comment]
Oh, I understand now. 
The new version of plotlyJs changed the default behavior of `hovermode` I think.
I have added `hovermode` now to the settings, please update the package to the latest version ([v1.1.13](https://pypi.org/project/tensorboard-plugin-customizable-plots/1.1.3/)) and set `hovermode` (`Settings > Layout Settings > hovermode`) to `x` to achieve the behavior of the first image.  
Let me know if that fixed the issue ?

**Comment by MinsGoing** [comment]
Thank you for the update. It's working now！
